// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfePeGWHk-UNkT6lZd4GeAHd1nT_I3Dc0',
    appId: '1:277033948129:web:d1603da3e30b9a083cb8a0',
    messagingSenderId: '277033948129',
    projectId: 'carrerlink-45f19',
    authDomain: 'carrerlink-45f19.firebaseapp.com',
    storageBucket: 'carrerlink-45f19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASmLe1PKO61NaNZfGlgy2jwu9R-_wDyaE',
    appId: '1:277033948129:android:d081b054d8abf14d3cb8a0',
    messagingSenderId: '277033948129',
    projectId: 'carrerlink-45f19',
    storageBucket: 'carrerlink-45f19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARpI99YzYJc2BW_x_CxRz9KbEbh_wOAlc',
    appId: '1:277033948129:ios:6a8f858bd14165213cb8a0',
    messagingSenderId: '277033948129',
    projectId: 'carrerlink-45f19',
    storageBucket: 'carrerlink-45f19.appspot.com',
    iosBundleId: 'com.dbestech.jobhub',
  );
}
